const $ = (id) => document.getElementById(id);
const career = $('career'), a = $('snapshot-a'), b = $('snapshot-b'), status = $('status'), result = $('result');
const get = (path) => fetch(path).then((response) => { if (!response.ok) throw new Error(`Request failed (${response.status})`); return response.json(); });
const option = (value, label) => { const item = document.createElement('option'); item.value = value; item.textContent = label; return item; };
let snapshots = [];
async function loadCareers() { const careers = await get('/api/careers'); career.replaceChildren(...careers.map((item) => option(item.id, item.label))); if (!careers.length) { a.replaceChildren(); b.replaceChildren(); status.textContent = 'No careers imported yet. Import or migrate a snapshot to begin.'; return; } await loadSnapshots(); }
async function loadSnapshots() { snapshots = await get(`/api/careers/${encodeURIComponent(career.value)}/snapshots`); const options = snapshots.map((item) => option(item.id, `${item.seasonLabel} · ${item.checkpoint} · ${item.sourceFilename}`)); a.replaceChildren(...options.map((item) => item.cloneNode(true))); b.replaceChildren(...options); if (snapshots.length > 1) { a.value = snapshots[0].id; b.value = snapshots.at(-1).id; } status.textContent = `${snapshots.length} immutable snapshot${snapshots.length === 1 ? '' : 's'} available.`; if (snapshots.length === 1) showSnapshot(snapshots[0].id); }
async function showSnapshot(id) { const snapshot = await get(`/api/snapshots/${encodeURIComponent(id)}`); const rows = snapshot.players.map((player) => `<div class="row"><span>${player.name.display} <span class="muted">#${player.playerId}</span></span><span>${player.overall ?? '—'} · ${player.preferredPositions.join('/') || '—'} · ${player.contractUntil ?? '—'}</span></div>`).join(''); const academy = snapshot.academyPlayers.map((player) => `<div class="row"><span>${player.name.display} <span class="muted">#${player.playerId}</span></span><span>tier ${player.tier ?? '—'} · ${player.monthsInSquad ?? '—'} months</span></div>`).join(''); const evidence = snapshot.evidence.map((item) => `<div class="row"><span>${item.normalizedField}</span><span>${item.classification}</span></div>`).join(''); result.innerHTML = `<div class="card"><h2>Senior players</h2><div class="metric">${snapshot.players.length}</div></div><div class="card"><h2>Academy players</h2><div class="metric">${snapshot.academyPlayers.length}</div></div><div class="card"><h2>Checkpoint</h2><div class="metric" style="font-size:22px">${snapshot.checkpoint}</div></div><div class="card" style="grid-column:1/-1"><h2>Squad snapshot</h2><div class="list">${rows || '<span class="muted">No senior players.</span>'}</div></div><div class="card" style="grid-column:1/-1"><h2>Academy</h2><div class="list">${academy || '<span class="muted">No academy players.</span>'}</div></div><div class="card"><h2>Evidence classifications</h2><div class="list">${evidence || '<span class="muted">No field evidence.</span>'}</div></div><div class="card"><h2>Integrity</h2><span class="muted">Source SHA-256</span><br>${snapshot.sourceSha256}<br><span class="muted">Parser ${snapshot.parserVersion}</span></div><div class="card" style="grid-column:1/-1"><a href="/api/snapshots/${encodeURIComponent(id)}/export.csv">Download CSV</a> · <a href="/api/snapshots/${encodeURIComponent(id)}/export.json">Download JSON</a></div>`; result.hidden = false; }
function render(data) { const updated = data.players.updated.map((item) => `<div class="row"><span>${item.name} <span class="muted">#${item.playerId}</span></span><span>${item.changes.map((change) => `${change.field}: ${change.before ?? '—'} → ${change.after ?? '—'}`).join(' · ')}</span></div>`).join(''); const joined = data.players.joined.map((item) => `<div class="row"><span>${item.name} <span class="muted">#${item.playerId}</span></span><span>joined · ${item.nameSource}</span></div>`).join(''); const departed = data.players.departed.map((item) => `<div class="row"><span>${item.name} <span class="muted">#${item.playerId}</span></span><span>departed · ${item.nameSource}</span></div>`).join(''); result.innerHTML = `<div class="card"><h2>Players joined</h2><div class="metric">${data.summary.playersJoined}</div></div><div class="card"><h2>Players departed</h2><div class="metric">${data.summary.playersDeparted}</div></div><div class="card"><h2>Players updated</h2><div class="metric">${data.summary.playersUpdated}</div></div><div class="card" style="grid-column:1/-1"><h2>Joined</h2><div class="list">${joined || '<span class="muted">None</span>'}</div><h2>Departed</h2><div class="list">${departed || '<span class="muted">None</span>'}</div><h2>Field changes</h2><div class="list">${updated || '<span class="muted">No player fields changed.</span>'}</div></div>`; result.hidden = false; }
const toBase64 = (buffer) => { let binary = ''; const bytes = new Uint8Array(buffer); for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return btoa(binary); };
let pendingPreview = null;
async function previewSnapshot() { const file = $('save-file').files[0]; if (!file) { $('preview').textContent = 'Choose an Apollo-exported DATA file first.'; return; } status.textContent = 'Hashing, staging, and parsing…'; const response = await fetch('/api/import/preview', { method: 'POST', headers: {'content-type': 'application/json'}, body: JSON.stringify({ filename: file.name, dataBase64: toBase64(await file.arrayBuffer()) }) }); pendingPreview = await response.json(); if (!response.ok) throw new Error(pendingPreview.error ?? `Preview failed (${response.status})`); $('preview').textContent = `${pendingPreview.careerHint} · ${pendingPreview.candidate.players} senior · ${pendingPreview.candidate.academyPlayers} academy · SHA-256 ${pendingPreview.sourceSha256}`; $('career-label').value = pendingPreview.careerHint; const careers = await get('/api/careers'); $('career-choice').replaceChildren(option('new', 'Create new Career'), ...careers.map((item) => option(item.id, `Use existing: ${item.label}`))); $('metadata').hidden = false; status.textContent = 'Preview ready. Confirm metadata to commit.'; }
async function importSnapshot() { if (!pendingPreview) return; const choice = $('career-choice').value; const body = { token: pendingPreview.token, seasonLabel: $('season').value || 'unknown', checkpoint: $('checkpoint').value, careerLabel: $('career-label').value || pendingPreview.careerHint }; if (choice !== 'new') body.careerId = choice; const committed = await fetch('/api/import/commit', { method: 'POST', headers: {'content-type': 'application/json'}, body: JSON.stringify(body) }); const resultBody = await committed.json(); if (!committed.ok) throw new Error(resultBody.error ?? `Commit failed (${committed.status})`); pendingPreview = null; $('metadata').hidden = true; status.textContent = `Imported snapshot ${resultBody.snapshotId}`; await loadCareers(); }
career.addEventListener('change', loadSnapshots); a.addEventListener('change', () => showSnapshot(a.value).catch((error) => { status.textContent = error.message; })); $('compare').addEventListener('click', async () => { if (!a.value || !b.value) return; status.textContent = 'Comparing snapshots…'; try { render(await get(`/api/compare?a=${encodeURIComponent(a.value)}&b=${encodeURIComponent(b.value)}`)); status.textContent = 'Live comparison'; } catch (error) { status.textContent = error.message; } });
$('preview-button').addEventListener('click', () => previewSnapshot().catch((error) => { status.textContent = error.message; })); $('import').addEventListener('click', () => importSnapshot().catch((error) => { status.textContent = error.message; }));
loadCareers().catch((error) => { status.textContent = error.message; });
