const $ = (id) => document.getElementById(id);
const career = $('career'), a = $('snapshot-a'), b = $('snapshot-b'), status = $('status'), result = $('result');
const get = (path) => fetch(path).then((response) => { if (!response.ok) throw new Error(`Request failed (${response.status})`); return response.json(); });
const option = (value, label) => { const item = document.createElement('option'); item.value = value; item.textContent = label; return item; };
let snapshots = [];
async function loadCareers() { const careers = await get('/api/careers'); career.replaceChildren(...careers.map((item) => option(item.id, item.label))); await loadSnapshots(); }
async function loadSnapshots() { snapshots = await get(`/api/careers/${encodeURIComponent(career.value)}/snapshots`); const options = snapshots.map((item) => option(item.id, `${item.seasonLabel} · ${item.checkpoint} · ${item.sourceFilename}`)); a.replaceChildren(...options.map((item) => item.cloneNode(true))); b.replaceChildren(...options); if (snapshots.length > 1) { a.value = snapshots[0].id; b.value = snapshots.at(-1).id; } status.textContent = `${snapshots.length} immutable snapshot${snapshots.length === 1 ? '' : 's'} available.`; }
function render(data) { const updated = data.players.updated.map((item) => `<div class="row"><span>${item.name} <span class="muted">#${item.playerId}</span></span><span>${item.changes.length} fields</span></div>`).join(''); result.innerHTML = `<div class="card"><h2>Players joined</h2><div class="metric">${data.summary.playersJoined}</div></div><div class="card"><h2>Players departed</h2><div class="metric">${data.summary.playersDeparted}</div></div><div class="card"><h2>Players updated</h2><div class="metric">${data.summary.playersUpdated}</div></div><div class="card" style="grid-column:1/-1"><h2>Updated player details</h2><div class="list">${updated || '<span class="muted">No player fields changed.</span>'}</div></div>`; result.hidden = false; }
career.addEventListener('change', loadSnapshots); $('compare').addEventListener('click', async () => { if (!a.value || !b.value) return; status.textContent = 'Comparing snapshots…'; try { render(await get(`/api/compare?a=${encodeURIComponent(a.value)}&b=${encodeURIComponent(b.value)}`)); status.textContent = 'Live comparison'; } catch (error) { status.textContent = error.message; } });
loadCareers().catch((error) => { status.textContent = error.message; });
