const $ = (id) => document.getElementById(id);
const career = $('career'), a = $('snapshot-a'), b = $('snapshot-b'), status = $('status'), result = $('result');
const get = (path) => fetch(path).then((response) => { if (!response.ok) throw new Error(`Request failed (${response.status})`); return response.json(); });
const option = (value, label) => { const item = document.createElement('option'); item.value = value; item.textContent = label; return item; };
let snapshots = [];
async function loadCareers() { const careers = await get('/api/careers'); career.replaceChildren(...careers.map((item) => option(item.id, item.label))); if (!careers.length) { a.replaceChildren(); b.replaceChildren(); status.textContent = 'No careers imported yet. Import or migrate a snapshot to begin.'; return; } await loadSnapshots(); }
async function loadSnapshots() { snapshots = await get(`/api/careers/${encodeURIComponent(career.value)}/snapshots`); const options = snapshots.map((item) => option(item.id, `${item.seasonLabel} · ${item.checkpoint} · ${item.sourceFilename}`)); a.replaceChildren(...options.map((item) => item.cloneNode(true))); b.replaceChildren(...options); if (snapshots.length > 1) { a.value = snapshots[0].id; b.value = snapshots.at(-1).id; } status.textContent = `${snapshots.length} immutable snapshot${snapshots.length === 1 ? '' : 's'} available.`; }
function render(data) { const updated = data.players.updated.map((item) => `<div class="row"><span>${item.name} <span class="muted">#${item.playerId}</span></span><span>${item.changes.length} fields</span></div>`).join(''); result.innerHTML = `<div class="card"><h2>Players joined</h2><div class="metric">${data.summary.playersJoined}</div></div><div class="card"><h2>Players departed</h2><div class="metric">${data.summary.playersDeparted}</div></div><div class="card"><h2>Players updated</h2><div class="metric">${data.summary.playersUpdated}</div></div><div class="card" style="grid-column:1/-1"><h2>Updated player details</h2><div class="list">${updated || '<span class="muted">No player fields changed.</span>'}</div></div>`; result.hidden = false; }
const toBase64 = (buffer) => { let binary = ''; const bytes = new Uint8Array(buffer); for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return btoa(binary); };
async function importSnapshot() { const file = $('save-file').files[0]; if (!file) { $('preview').textContent = 'Choose an Apollo-exported DATA file first.'; return; } status.textContent = 'Hashing, staging, and parsing…'; const response = await fetch('/api/import/preview', { method: 'POST', headers: {'content-type': 'application/json'}, body: JSON.stringify({ filename: file.name, dataBase64: toBase64(await file.arrayBuffer()) }) }); const preview = await response.json(); if (!response.ok) throw new Error(preview.error ?? `Import failed (${response.status})`); $('preview').textContent = `${preview.careerHint} · ${preview.candidate.players} senior · ${preview.candidate.academyPlayers} academy · SHA-256 ${preview.sourceSha256}`; const committed = await fetch('/api/import/commit', { method: 'POST', headers: {'content-type': 'application/json'}, body: JSON.stringify({ token: preview.token, seasonLabel: $('season').value || 'unknown', checkpoint: $('checkpoint').value, careerLabel: preview.careerHint, note: '' }) }); const resultBody = await committed.json(); if (!committed.ok) throw new Error(resultBody.error ?? `Commit failed (${committed.status})`); status.textContent = `Imported snapshot ${resultBody.snapshotId}`; await loadCareers(); }
career.addEventListener('change', loadSnapshots); $('compare').addEventListener('click', async () => { if (!a.value || !b.value) return; status.textContent = 'Comparing snapshots…'; try { render(await get(`/api/compare?a=${encodeURIComponent(a.value)}&b=${encodeURIComponent(b.value)}`)); status.textContent = 'Live comparison'; } catch (error) { status.textContent = error.message; } });
$('import').addEventListener('click', () => importSnapshot().catch((error) => { status.textContent = error.message; }));
loadCareers().catch((error) => { status.textContent = error.message; });
