export interface SeasonRecord { readonly season: number | null; readonly teamId?: number | null; readonly leagueId?: number | null; readonly played: number; readonly wins: number; readonly draws: number; readonly losses: number; readonly points: number | null; readonly position: number | null; readonly goalsFor: number | null; readonly goalsAgainst: number | null; readonly leagueTrophies: number; readonly cupTrophies: number; readonly bigBuy?: { readonly playerName: string; readonly amount: number } | null; readonly bigSell?: { readonly playerName: string; readonly amount: number } | null; readonly objectives?: { readonly league: number | null; readonly leagueResult: number | null; readonly domesticCup: number | null; readonly domesticCupResult: number | null; readonly europeCup: number | null; readonly europeCupResult: number | null } }
export interface CompetitionProgress { readonly name: string; readonly season: number | null; readonly stage: number | null; readonly won: boolean; readonly result: number | null }
export interface LeagueStanding { readonly teamId: number; readonly teamName: string; readonly position: number | null; readonly previousPosition: number | null; readonly played: number; readonly wins: number; readonly draws: number; readonly losses: number; readonly goalsFor: number; readonly goalsAgainst: number; readonly points: number; readonly isUserClub: boolean }
export interface LeagueFacts { readonly leagueId: number | null; readonly leagueName: string | null; readonly standings: readonly LeagueStanding[]; readonly statsSource?: 'league_links' | 'manager_history_overlay' | 'unavailable' }
export interface TransferActivity { readonly playerId: number; readonly teamId: number | null; readonly offerTeamId: number | null; readonly offeredFee: number | null; readonly offeredWage: number | null; readonly signedDate: number | null; readonly completionDate: number | null; readonly contractType: number | null; readonly isComingThisSeason: boolean; readonly isLoanBuy: boolean; readonly directApproach: boolean }
export interface TransferEvent { readonly playerId: number; readonly playerName: string | null; readonly fromTeamId: number | null; readonly fromTeamName: string | null; readonly toTeamId: number | null; readonly toTeamName: string | null; readonly date: number | null; readonly eventId: number }
export interface PlayerGrowthState { readonly playerId: number; readonly overall: number | null; readonly attributes: Readonly<Record<string, number>> }
export interface SquadRanking { readonly playerId: number; readonly currentOverall: number | null; readonly previousOverall: number | null }
export interface FixtureRecord { readonly date: number; readonly kickoff: number | null; readonly competitionId: number; readonly slotA: number; readonly slotB: number; readonly goalsA: number | null; readonly goalsB: number | null }
export interface MatchResultRecord { readonly date: number; readonly homeTeamId: number; readonly awayTeamId: number; readonly homeGoals: number; readonly awayGoals: number; readonly leagueId: number; readonly standoutPlayerId: number | null }
export interface FixtureEvidence { readonly fixtures: readonly FixtureRecord[]; readonly latestResults: readonly MatchResultRecord[]; readonly source: 'companion-fixture-ledger'; readonly fixtureCount: number; readonly resultCount: number }
export interface CareerFacts { readonly managerReputation: number | null; readonly managerWage: number | null; readonly totalEarnings: number | null; readonly clubWorth: number | null; readonly profitability: number | null; readonly domesticPrestige: number | null; readonly internationalPrestige: number | null; readonly youthDevelopment: number | null; readonly transferBudget: number | null; readonly wageBudget: number | null; readonly biggestWin: { readonly userScore: number; readonly opponentScore: number | null; readonly opponentTeamId: number | null; readonly date: number } | null; readonly biggestLoss: { readonly userScore: number; readonly opponentScore: number | null; readonly opponentTeamId: number | null; readonly date: number } | null; readonly releasedPlayersThisSeason?: number | null; readonly boardConfidence?: number | null; readonly seasons: readonly SeasonRecord[]; readonly competitions: readonly CompetitionProgress[]; readonly league: LeagueFacts | null; readonly transfers?: readonly TransferActivity[]; readonly transferEvents?: readonly TransferEvent[]; readonly playerGrowth?: readonly PlayerGrowthState[]; readonly squadRanking?: readonly SquadRanking[]; readonly fixtureEvidence?: FixtureEvidence | null }
