import { DB_HEADER, scanDatabaseBlocks } from './container.js';
import type { DbMeta } from './meta.js';
export type FieldValue = string | number | null; export type Row = Record<string, FieldValue>; export type Tables = Record<string, Row[]>;
export interface TableStats { table: string; rows: number; fields: number; recordSize: number; unknownFields: string[] }
export interface ParseResult { tables: Tables; databases: { index: number; tables: string[] }[]; unknownTables: string[]; stats: TableStats[] }
class Reader { constructor(readonly bytes: Buffer, public position = 0) {} u8() { return this.bytes[this.position++]!; } u16() { const v = this.bytes.readUInt16LE(this.position); this.position += 2; return v; } u32() { const v = this.bytes.readUInt32LE(this.position); this.position += 4; return v; } skip(n: number) { this.position += n; } bytesOf(n: number) { const v = this.bytes.subarray(this.position, this.position + n); this.position += n; return v; } }
interface Field { type: number; bitOffset: number; bitDepth: number; key: string; known: boolean; short: string }
const intField = 3; const stringField = 0; const floatField = 4;
function readBlock(block: Buffer, meta: DbMeta, wanted?: ReadonlySet<string>): { tables: Tables; unknownTables: string[]; stats: TableStats[] } {
  const r = new Reader(block, DB_HEADER.length); const declared = r.u32(); if (declared !== block.length) throw new Error(`database size mismatch: ${declared} != ${block.length}`); r.skip(4); const count = r.u32(); r.skip(4); const names: string[] = []; const offsets: number[] = []; for (let i = 0; i < count; i++) { names.push(r.bytesOf(4).toString('latin1')); offsets.push(r.u32()); } r.skip(4); const tableStart = r.position; const tables: Tables = {}; const unknownTables: string[] = []; const stats: TableStats[] = [];
  names.forEach((short, index) => { const table = meta.tableNames.get(short); if (!table) { unknownTables.push(short); return; } if (wanted && !wanted.has(table)) return; r.position = tableStart + offsets[index]!; r.skip(4); const recordSize = r.u32(); r.skip(10); const rows = r.u16(); r.skip(4); const fieldCount = r.u8(); r.skip(11); const fields: Field[] = []; for (let f = 0; f < fieldCount; f++) { const type = r.u32(); const bitOffset = r.u32(); const shortField = r.bytesOf(4).toString('latin1'); const bitDepth = r.u32(); const key = meta.fieldNames.get(shortField) ?? `unk_${shortField}`; fields.push({ type, bitOffset, bitDepth, key, known: meta.fieldNames.has(shortField), short: shortField }); } fields.sort((a, b) => a.bitOffset - b.bitOffset); stats.push({ table, rows, fields: fieldCount, recordSize, unknownFields: fields.filter((f) => !f.known).map((f) => f.short) }); const decoded: Row[] = []; for (let rowIndex = 0; rowIndex < rows; rowIndex++) { const start = r.position; const row: Row = {}; let carry = 0; let carryBits = 0; for (const field of fields) { if (field.type === stringField) { r.position = start + (field.bitOffset >> 3); row[field.key] = r.bytesOf(field.bitDepth >> 3).toString('utf8').replace(/\0+$/, '') || null; carry = 0; carryBits = 0; } else if (field.type === floatField) { r.position = start + (field.bitOffset >> 3); row[field.key] = r.u32(); carry = 0; carryBits = 0; } else if (field.type === intField) { const depth = field.bitDepth; let raw = carryBits ? carry >>> carryBits : 0; let bit = carryBits ? 8 - carryBits : 0; while (bit < depth) { carry = r.u8(); raw += carry * 2 ** bit; bit += 8; } carryBits = (depth + 8 - bit) & 7; row[field.key] = (raw % 2 ** depth) + (meta.fieldRange.get(table + field.key) ?? 0); } else row[field.key] = null; } r.position = start + recordSize; decoded.push(row); } tables[table] = decoded; }); return { tables, unknownTables, stats };
}
export function parseDatabaseSave(save: Buffer, meta: DbMeta, wanted?: Iterable<string>): ParseResult { const blocks = scanDatabaseBlocks(save); if (!blocks.length) throw new Error('no DB database found in save'); const want = wanted ? new Set(wanted) : undefined; const tables: Tables = {}; const databases: ParseResult['databases'] = []; const unknownTables: string[] = []; const stats: TableStats[] = []; blocks.forEach((block, index) => { const result = readBlock(block.bytes, meta, want); databases.push({ index, tables: Object.keys(result.tables).sort() }); unknownTables.push(...result.unknownTables); stats.push(...result.stats); for (const [name, rows] of Object.entries(result.tables)) (tables[name] ??= []).push(...rows); }); return { tables, databases, unknownTables: [...new Set(unknownTables)], stats }; }
